version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${PGDATA}
    volumes:
      - ${DATA_PATH}:/data
      - ${CONFIG_PATH}:/config
    ports:
      - "${POSTGRES_PORT}:5432"
    command: -c 'config_file=/config/postgresql.conf'
